### ISSUE TITLE
예약 검색 시 페이지네이션이 제대로 작동하지 않음

### ISSUE THREAD

**Issue by naranghae** [jiphyeonjeon-42/backend-nest-legacy#117]
## description
> 예약 검색 시 검색 값이 제대로 나오지 않는 현상
## todo
- [x] filter=proceeding 일 때 정상 작동 하는가
- [x] filter=finish일 때 정상 작동 하는가
- [x] filter=proceeding, finish 일 때 정상 작동 하는가
