### ISSUE TITLE
jwt 토큰 생성 로직 수정

### ISSUE THREAD

**Issue by DiceMono** [jiphyeonjeon-42/backend-nest-legacy#31]
## description
req.user.id 가 intra 대신 db에 저장된 user의 id를 가리킵니다.
추가사항: reservation 의 endAt에 nullable: true 옵션을 추가합니다.
## todo
- [x] auth 모듈 수정
- [x] users 모듈 수정
- [x] reservation 엔티티의 endAt 수정
