### ISSUE TITLE
42 Oauth 로그인

### ISSUE THREAD

**Issue by naranghae** [jiphyeonjeon-42/backend-nest-legacy#5]
## description
> 42 Oauth로 로그인한  유저정보를 연동된 DB에 저장합니다.
## todo
- [x] 42 Oauth로 유저 정보 가져오기
- [x] DB repository 만들기
- [x] USER 정보 validation 검사하기
- [x] 인증 Guard 만들기 
- [x] 쿠키 만들기
- [x] 로그인 시 DB정보 조회 후 FE에 이미지, loginID를 전달하기
- [ ] 테스트 코드 작성하기
