### ISSUE TITLE
배포를 위한 github action 작성

### ISSUE THREAD

**Issue by DiceMono** [jiphyeonjeon-42/backend-nest-legacy#63]
## description
배포를 위한 github action 파일 작성
## todo
- [x] github action 파일 작성
- [x] appspec.yaml 파일 작성
- [x] github secrets 관리
